### ISSUE TITLE
playlists return only 25 items, even if there are many more in the playlist.

### ISSUE THREAD

**Issue by gdavis** [kylejginavan/youtube_it#111]
Youtube sets the default number of items returned in a playlist to 25, and allows a maximum of 50. Currently it seems youtube_it will always return 25 results, and will omit the rest.

Is there a way to specify counts and a start index in order to paginate the results? Or can it just be built in? Thanks!

**Comment by chebyte** [comment]
now we added a fix on that you have to use it like this

```
playlists_first_page = @client.playlists('sbnation', {'start-index' => 1, 'max-results' => 25})
```

   playlists_second_page = @client.playlists('sbnation', {'start-index' => 26, 'max-results' => 25})

this change is just in the current branch we going to do the release soon, but you can clone from master if you need test it now
