### ISSUE TITLE
Subscribe To Channel

### ISSUE THREAD

**Issue by pwgustafson** [kylejginavan/youtube_it#112]
When using:

client.subscribe_channel(channel_name), 

youtube accepts two options, the youtube user name, and the category.

It would be great if we could provide additional parameters to specify whetherwe are adding a subscription for the user or for the channel.  See docs:

https://developers.google.com/youtube/2.0/developers_guide_protocol_subscriptions#Adding_a_subscription

**Comment by chebyte** [comment]
thanks we going to add this one soon!
