### ISSUE TITLE
How to address problems with upload timeout without log output?

### ISSUE THREAD

**Issue by ylluminate** [kylejginavan/youtube_it#113]
I'm having a problem where `video_upload` is not giving any indication as to why it's timing out on upload attempts.  It seems to work sometimes and others not, however I need some kind of verbose log output in order to address the situation.

I'm not on Rails (just a ruby script) and am wondering what is the correct method of accessing failure output for this method?

**Comment by chebyte** [comment]
if the video is uploaded ok it going to returns the video object, if it returns empty or some execption is cause it is getting some error, you can run debug mode 

adding :debug => true  in the initializer

and see in console how works this
