### ISSUE TITLE
Is youtube_it compatible with YouTube API v3.0 Experimental version?

### ISSUE THREAD

**Issue by designium** [kylejginavan/youtube_it#117]
Hi,

I want to know if youtube_it current version is compatible with the new YT API v3.

Cheers.

**Comment by chebyte** [comment]
for the moment we dont support this one but we going to do that soon

cheers!

**Comment by shanab** [comment]
Any updates on integration youtube_it with Youtube API v3?

**Comment by hyperrjas** [comment]
+1. I can not create a new dev key from api v2 because is deprecated from google page, so I can not use this gem with new youtube api key. I have opened a issue https://github.com/kylejginavan/youtube_it/issues/202

Thanks!
