### ISSUE TITLE
Add Support for Google Service Accounts

### ISSUE THREAD

**Issue by jasonreposa** [kylejginavan/youtube_it#128]
Google is now recommending to use "service accounts" in applications that use server to server communication, as opposed to granting one user access via authorization code.

I'm looking into writing a patch, but I'm having issues figuring out JWT (JSON config) and where to apply the cert. I'm sure someone with a bit more experience could figure this out really quickly.

More here:
https://developers.google.com/accounts/docs/OAuth2ServiceAccount

**Comment by odarriba** [comment]
Maybe this could help you. I've used it in a project and there's a bug that changes some characters.

If anyone want to do a patch for youtube_it I could find what characters to change to make the output valid.

https://github.com/progrium/ruby-jwt

**Comment by chebyte** [comment]
can you share the code that you are writing?

thanks

**Comment by magpieuk** [comment]
Has there been any progress in this area? I need to do an app similar to the demo one where its only connecting to a single youtube account and managing videos. Cant seem to get my head around how to do this with OAuth2 but service accounts sound right.

Any other good pointers on using the Oauth2 with the gem, wiki article not quite enough to get it into my head,

**Comment by subimage** [comment]
Dead in the water?
