### ISSUE TITLE
All videos from playlist

### ISSUE THREAD

**Issue by bodrovis** [kylejginavan/youtube_it#142]
Hello. I'm using the construction:

playlist = client.playlist(playlist_id)
all_videos = playlist.videos

to get all videos from some playlist. But i'm able to get only the first 25 videos, whereas there are more than 60 videos.

How can i specify the "max-results" parameter (something like per_page in the example videos_by(:query => "penguin", :page => 2, :per_page => 15))?

**Comment by bodrovis** [comment]
Oops sorry - duplication with this https://github.com/kylejginavan/youtube_it/issues/111

But was that fix actually applied? Or should i still use

playlists_first_page = @client.playlists('sbnation', {'start-index' => 1, 'max-results' => 25})

**Comment by chebyte** [comment]
hi there, question , this works for you?

```
playlists_first_page = @client.playlists('sbnation', {'start-index' => 1, 'max-results' => 25})
playlists_second_page = @client.playlists('sbnation', {'start-index' => 26, 'max-results' => 25})
```

**Comment by bodrovis** [comment]
This works, but @client.playlists returns playlists with their ids, descriptions and titles, not videos (just tried). Whereas i have to fetch **all** videos from **one** playlist. When i try to use {'start-index' => 1, 'max-results' => 25} as an argument like this 

client.playlist(playlist_id, {'start-index' => 1, 'max-results' => 25})

i get an error, because there can be only insructions for sorting.

**Comment by chebyte** [comment]
oka let me see the error

**Comment by bodrovis** [comment]
If i use

```
    playlist = client.playlist(playlist_id, {'start-index' => 1, 'max-results' => 25})
```

I get the following error:

**Invalid value for orderby parameter: {"start-index"=>1, "max-results"=>25}: invalidParameterValue**

Strangely enough this error is called UploadError in VideosController#get_from_playlist 

I browsed the source code and found this method:

def playlist(playlist_id, order_by = :position)

So it does not allow to pass any "start-index" or "max-results" parameters. Maybe there is some other way?

**Comment by chebyte** [comment]
if you see here

https://developers.google.com/youtube/2.0/developers_guide_protocol_playlists#Retrieving_a_playlist

the playlist tag just can receive as params position no more, so the gem is ok

but I going to think the way for list more than 25 videos

do you have the playlist id with more than 25 videos?

**Comment by bodrovis** [comment]
Yes, this one for example: http://www.youtube.com/playlist?list=PL2FD8A33E3A221A86

**Comment by abotalov** [comment]
Playlist may contain up to 200 videos. YT API provides access to all videos using `max-results` and `start-index` params that (I believe) are supported by all requests - see https://developers.google.com/youtube/2.0/developers_guide_protocol_api_query_parameters#Standard_parameters

See this url as an example:
http://gdata.youtube.com/feeds/api/playlists/PLbpi6ZahtOH5T_nrvCoHfnYWbW1shGYYv?max-results=50&start-index=51

#videos method doesn't use `max-results` and `start-index` params (its url is
`http://gdata.youtube.com/feeds/api/playlists/#{playlist_id}?v=2`)  so I think this issue should be reopened.

**Comment by andrewroth** [comment]
I used the following to get all the videos from a playlist.  Maybe it can be used to fix this issue somewhere.

```
def all_videos_from_playlist(playlist_id)
  all_videos = []
  start_index, page_size = 1, 50

  begin
    newest_videos = @yt.playlist(playlist_id, {'start-index' => start_index, 'max-results' => page_size}).videos
    all_videos += newest_videos
    start_index += page_size
  end while newest_videos && newest_videos.size == page_size

  all_videos
end
```

**Comment by bodrovis** [comment]
I can confirm that method suggested by @andrewroth works. Thanks a lot!
