### ISSUE TITLE
Playlist returns empty videos collection

### ISSUE THREAD

**Issue by vikaswadhwa** [kylejginavan/youtube_it#143]
I have the following code:

@playlists.first

which pulls back just fine and returns the correct playlist object (titled "Award Winning Films")

but when I try to access the playlist videos:

@playlists.first.videos

The object is not nil, but the set is empty. Turning it to a string returns an empty bracket and doing a loop via each

@playlists.first.videos.each

does not create a single loop.

The playlist in question is here:

http://www.youtube.com/playlist?list=PLBj8ekDUM_NCWgZp7vPXSxuyKHelJvsvU

So we know that at least one video exists. Suggestions?

**Comment by chebyte** [comment]
hey there for me is working fine

```
p =  client.playlist("PLBj8ekDUM_NCWgZp7vPXSxuyKHelJvsvU")
puts p.videos.first.title #Grinning Demons (based on 'Seed' by Ania Ahlborn)
```

as you see I can read fine the video

cheers

**Comment by vikaswadhwa** [comment]
Turns out I misunderstood and didn't realize that I needed separate API calls to grab the list of playlists THEN the list of videos for EACH playlist.
