### ISSUE TITLE
Cannot search by tags and user at the same time.

### ISSUE THREAD

**Issue by stpn** [kylejginavan/youtube_it#145]
client.videos_by(:user => "nba", :tags => ["mercedes"])

returns videos that have nothing to do with mercedes (just videos from user), basically same results as  client.videos_by(:user => "nba", :tags => ["playoffs"])

while 
http://gdata.youtube.com/feeds/api/users/nba/uploads?category=playoffs&alt=json
http://gdata.youtube.com/feeds/api/users/nba/uploads?category=playoffs&alt=json

Or am I missing something?

**Comment by chebyte** [comment]
hey there thanks for the advice the params :user is just for use for users search, but if you need filter by user you have to use author param like this

```
client.videos_by(:author => "nba", :tags => ["playoffs"])
```

cheers
