### ISSUE TITLE
HTML5 embed is not working as expected

### ISSUE THREAD

**Issue by reydelleon** [kylejginavan/youtube_it#150]
I'm using the embed_html5 method to show a video in my page. Tha problem is that when I load the page, I'm getting the common Flash player youtube privides. I was expecting a <video> tag, since that's HTML5 way for showing video, but I'm getting an iframe as normal embed would do. It is that the normal behavior for Youtube_it? If it is, how can I get the video url from youtube it returned video object to use a custom code to show the video?

**Comment by chebyte** [comment]
youtube html5 use iframe, this behavior is expected

http://apiblog.youtube.com/2010/07/new-way-to-embed-youtube-videos.html

thanks
