### ISSUE TITLE
Upgrade Youtube API to version 2.1

### ISSUE THREAD

**Issue by KieranP** [kylejginavan/youtube_it#151]
https://github.com/kylejginavan/youtube_it/pull/138 had changes that weren't pulled in, like updating the GData-Version from 2 to 2.1, and fixing any issues...

Please update the API version. An application I'm working on needs some of the newer 2.1 features.

**Comment by bobbytables** [comment]
+1 This is desperately needed.

**Comment by bobbytables** [comment]
@kylejginavan To reiterate, there are some issues with connecting accounts to Google+ that aren't available to the Youtube Data Api 2.0, when this happens people will start getting 40(\d) 's

**Comment by chebyte** [comment]
ok I'm working on that tomorrow I think that we going to launch the new release

thanks for all!
