### ISSUE TITLE
Client suddenly stops working

### ISSUE THREAD

**Issue by grandwazir** [kylejginavan/youtube_it#156]
I have recently used youtube_it to create a simple command line uploader for my own use. I am using the username, password, devkey method of authentication. It has suddenly stopped working though giving me the following stack trace:

```
AuthenticationError: AuthenticationError
from /var/lib/gems/1.9.1/gems/youtube_it-2.1.13/lib/youtube_it/request/video_upload.rb:529:in `auth_token'
from /var/lib/gems/1.9.1/gems/youtube_it-2.1.13/lib/youtube_it/request/video_upload.rb:476:in `authorization_headers'
from /var/lib/gems/1.9.1/gems/youtube_it-2.1.13/lib/youtube_it/request/video_upload.rb:645:in `block in yt_session'
from /var/lib/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:59:in `initialize'
from /var/lib/gems/1.9.1/gems/faraday-0.8.7/lib/faraday.rb:11:in `new'
from /var/lib/gems/1.9.1/gems/faraday-0.8.7/lib/faraday.rb:11:in `new'
from /var/lib/gems/1.9.1/gems/youtube_it-2.1.13/lib/youtube_it/request/video_upload.rb:637:in `yt_session'
from /var/lib/gems/1.9.1/gems/youtube_it-2.1.13/lib/youtube_it/request/video_upload.rb:179:in `get_my_videos'
from /var/lib/gems/1.9.1/gems/youtube_it-2.1.13/lib/youtube_it/client.rb:268:in `my_videos'
```

This only happens when trying to do something user specific such as upload a video or list uploaded videos. I am at a loss here since my credentials are correct and I can not get it to work with a brand new youtube account either.

I've traced back the error as far as I can but I don't understand what the error is trying to tell me.

**Comment by kmandreza** [comment]
This seems to be happening because Google moved the auth url from http://www.google.com/youtube/accounts/ClientLogin to http://www.google.com/accounts/ClientLogin. The auth_token method in video_upload.rb needs to be updated accordingly.

**Comment by joehwang** [comment]
This solved my trouble, thank you!

**Comment by kmandreza** [comment]
Nice!

**Comment by chebyte** [comment]
tomorrow we going to launch a new release with this fix!

thanks!
