### ISSUE TITLE
Thumbnail name attribute is always nil

### ISSUE THREAD

**Issue by extrafox** [kylejginavan/youtube_it#158]
Example result:

[#<YouTubeIt::Model::Thumbnail:0x9115cd4 @url="http://i.ytimg.com/vi/AP4m2ireYeQ/default.jpg", @height=90, @width=120, @time="00:01:28.500", @name=nil>, #<YouTubeIt::Model::Thumbnail:0x924eeac @url="http://i.ytimg.com/vi/AP4m2ireYeQ/mqdefault.jpg", @height=180, @width=320, @time=nil, @name=nil>, #<YouTubeIt::Model::Thumbnail:0x93df9d8 @url="http://i.ytimg.com/vi/AP4m2ireYeQ/hqdefault.jpg", @height=360, @width=480, @time=nil, @name=nil>, #<YouTubeIt::Model::Thumbnail:0x9574640 @url="http://i.ytimg.com/vi/AP4m2ireYeQ/sddefault.jpg", @height=480, @width=640, @time=nil, @name=nil>, #<YouTubeIt::Model::Thumbnail:0x9a2e21c @url="http://i.ytimg.com/vi/AP4m2ireYeQ/1.jpg", @height=90, @width=120, @time="00:00:44.250", @name=nil>, #<YouTubeIt::Model::Thumbnail:0x9a6f280 @url="http://i.ytimg.com/vi/AP4m2ireYeQ/2.jpg", @height=90, @width=120, @time="00:01:28.500", @name=nil>, #<YouTubeIt::Model::Thumbnail:0x9d993c0 @url="http://i.ytimg.com/vi/AP4m2ireYeQ/3.jpg", @height=90, @width=120, @time="00:02:12.750", @name=nil>]

**Comment by chebyte** [comment]
is working fine check please

```
video = @client.video_by("oFT7vWyC1Ys")
puts video.thumbnails.first.inspect
#<YouTubeIt::Model::Thumbnail:0x007fe9b4a626d8 @url="http://i.ytimg.com/vi/oFT7vWyC1Ys/default.jpg", @height=90, @width=120, @time="00:03:45.500", @name="default">
```

remember that it return an object no string

**Comment by extrafox** [comment]
Thanks for your response.

Here's what I get:

irb(main):002:0> video = ApplicationHelper.yt_client.video_by("oFT7vWyC1Ys")
irb(main):003:0> puts video.thumbnails.first.inspect
#<YouTubeIt::Model::Thumbnail:0xaf17890 @url="
http://i.ytimg.com/vi/oFT7vWyC1Ys/default.jpg", @height=90, @width=120,
@time="00:03:45.500", @name=nil>
=> nil
irb(main):004:0> video.thumbnails.first.name
=> nil

I've worked around it in my own application by using a regex on the url
field, but it seems like a legitimate bug.

I'm using youtube_it 2.1.13 from the gem.

Regards,

On Thu, Apr 25, 2013 at 8:55 AM, chebyte notifications@github.com wrote:

> is working fine check please
> 
> video = @client.video_by("oFT7vWyC1Ys")
> puts video.thumbnails.first.inspect
> #<YouTubeIt::Model::Thumbnail:0x007fe9b4a626d8 @url="http://i.ytimg.com/vi/oFT7vWyC1Ys/default.jpg", @height=90, @width=120, @time="00:03:45.500", @name="default">
> 
> remember that it return an object no string
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kylejginavan/youtube_it/issues/158#issuecomment-17015997
> .

## 

Christopher Taylor
em.xofartxe@extrafox.me // (206) 651-5123 \
Linkedinhttp://www.linkedin.com/in/ezln23
 // Twitter http://twitter.com/extrafox_ \ Blog http://extrafox.me/
