### ISSUE TITLE
Error (unable to convert video file)

### ISSUE THREAD

**Issue by judaro13** [kylejginavan/youtube_it#16]
Hi Im new using rails and I need upload vieos on youtube, so Im trying to use youtube_it but when I try to upload a flv movie trough the gem, the video seems to be uploaded but when I   consult it on youtube this error appear

Error (unable to convert video file)

Some idea?

**Comment by kylejginavan** [comment]
Howdy.  Thanks for using youtube_it.  Please put the *.flv file on http://ge.tt/ and I will take a look.

Best,
Kyle

**Comment by judaro13** [comment]
Hi thks for reply :), this is the sample video http://ge.tt/5h31EPG (I downloaded from youtube just for try and be sure that works), I try to upload directly from youtube page and was uploaded fine but trough my app I had "unable to convert video file"

Juliana

**Comment by chebyte** [comment]
hi there, the video is ok please check maybe you have already this video uploaded

you can try upload this making a little ruby script with this content

require 'rubygems'
require 'youtube_it'

client = YouTubeIt::Client.new(:username => "user", :password =>  "pass", :dev_key => "devkey")
client.video_upload(File.open("test.flv"), :title => "test rails",:description => 'sample', :category => 'People',:keywords => %w[test])

this works for me

Best,
mauro
