### ISSUE TITLE
Exception confusion

### ISSUE THREAD

**Issue by dbackeus** [kylejginavan/youtube_it#160]
The Error management in YouTubeIt looks like it could use some work.

_Non descriptive Errors_
I was confused to see `YouTubeIt::Upload::UploadError` being raised when what was actually failing was calling `my_video('id')` on a video which did not belong to the authenticated account. Having nothing to do with uploading.

Suggestion: UploadError should only ever happen when failing to upload a video. If possible a more descriptive error could be raised for the above example.

_Namespace confusion_
Both UploadError and AuthenticationError are defined in two places, and also with slightly different implementation (though the logic is actually the same). One of them in the Upload namespace suggesting that they are to do with uploading which the might not be. The other one in root namespace which seems like bad practice.

Suggestion: Keep all errors under the YouTubeIt namespace.

If you agree and would like some help I could look into cleaning this up.

**Comment by chebyte** [comment]
hi @dbackeus I agree with your idea, if you can please fix this
