### ISSUE TITLE
Add Video to Playlist need option to set video position

### ISSUE THREAD

**Issue by huyha85** [kylejginavan/youtube_it#163]
Hi,
I have used youtube_it for a while and it works great.
However, when I add a video to a playlist, I have no option to set the position of the video in playlist.
This feature seems to be very important as it allows user to order the videos in the list.
Should you please add it soon? As it's very simple (just add yt:position tag to xml)
Thank you,

**Comment by chebyte** [comment]
I just added and I added a new method for update the position too, check the readme 

thanks!
