### ISSUE TITLE
API v3 support & video searching only returning 100 results

### ISSUE THREAD

**Issue by odarriba** [kylejginavan/youtube_it#165]
Hello!

I'm pretty sure that this isn't problem of the gem, but today i have noticed that when I do a search, it only returns 100 results (with a search that used to return more results), and I don't know why.

I have searched about it in StackOverflow [http://stackoverflow.com/questions/16227540/need-help-to-get-more-than-100-results-using-youtube-search-api] and the thought that there is a problem with the Youtube Data API (making a petition by hand also returns 100 results) and they recommend to use the third version of the API.

Is there any plan to implement it?

Regards,

**Comment by chebyte** [comment]
can you show me the code that you are using?

thanks

**Comment by odarriba** [comment]
The error of 100 videos returned was due to an error in Google's servers. More details about this issue here: https://code.google.com/p/gdata-issues/issues/detail?id=4460

Also, it's recommended to port all the libraries to v3 of the API, but it's your decision xD

**Comment by chebyte** [comment]
@odarriba oka thanks a lot for your report, we going to move asap

cheers!

**Comment by odarriba** [comment]
Don't worry, your project makes my life easier :)
