### ISSUE TITLE
Updating profile information

### ISSUE THREAD

**Issue by mahhek** [kylejginavan/youtube_it#169]
After connecting via Oauth2 can user update his/her profile information? any method for that?

best,
Mahhek.

**Comment by chebyte** [comment]
hi there, nop you just can get the profile not update it!

**Comment by mahhek** [comment]
Can you please tell me how I can get that profile's information, not updating, please guide , thanks.

**Comment by mahhek** [comment]
@chebyte Please guide, thansks
