### ISSUE TITLE
Providing a means to obtain the total comment count.

### ISSUE THREAD

**Issue by rburton** [kylejginavan/youtube_it#17]
Can you provide a means to obtain the total comment count? I quickly modified the parser.rb file to include the following:

``` ruby
    class CommentsCountParser < FeedParser
      def parse_content(content)
        doc = REXML::Document.new(content.body)
        feed = doc.elements["feed"]
        feed.elements.each("openSearch:totalResults") do |total|
          return total.text.to_i
        end
      end
    end
```

Cheers,
Richard Burton III

**Comment by kylejginavan** [comment]
Hey Richard.  Sorry for not getting back sooner but I'm completely slammed at the moment.  I'll try to resolve this next week.  

Thanks for the contribution,
KG

**Comment by rburton** [comment]
I've clone that project and I'll work on some enhancements. If you like, feel free to pull them.

If there are some features you would like for someone to work on, I'll be willing to do that in order to contribute back.

Cheers,
Richard L. Burton III

**Comment by kylejginavan** [comment]
I do appreciate the enhancements.  If you provide a pull request I'll review and merge.

Thanks,
KG

**Comment by kylejginavan** [comment]
Hey Richard.  Have you had a second to provide a pull request for this?
