### ISSUE TITLE
Error in docs?

### ISSUE THREAD

**Issue by webdevotion** [kylejginavan/youtube_it#170]
Hello

Is the last line correct?

https://github.com/kylejginavan/youtube_it#video-queries
( subsection "standard queries" )

``` ruby
.....
$ client.get_all_videos(:top_rated, :time => :today)
```

From the source code it seems `get_all_videos` only accepts one argument:
https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/client.rb#L105

**Comment by chebyte** [comment]
this one is correct, cause opts is a hash

thanks!
