### ISSUE TITLE
is this better than using google's youtube api?

### ISSUE THREAD

**Issue by ghost** [kylejginavan/youtube_it#173]
noob question: why (or should I?) use this instead of google youtube api ?

**Comment by kylejginavan** [comment]
same reasons why you like to use ActiveRecord vrs. writing your own sql statements.

**Comment by ghost** [comment]
Thanks. I'll reread this later when I understand what activerecord is xD (the noobness abounds :) ) but i think I mainly got the gist of it

**Comment by kylejginavan** [comment]
Lets try this.  You can buy an iPhone to connect to AT&T's network or you can build your own phone.

**Comment by ghost** [comment]
what's the equivalent of buying an android phone that's not locked to a network? I think that's what I want xD

**Comment by kylejginavan** [comment]
doesn't exist to my knowledge and probably shouldn't.  it is better to have separate gems for your "network" youtube, vine, vimeo, etc.
