### ISSUE TITLE
Combining queries user and tags returns unexpected results

### ISSUE THREAD

**Issue by brianp** [kylejginavan/youtube_it#175]
In a query like

``` ruby
client.videos_by(:user => 'myuser', :tags => ['SomeTag'])
```

The tags parameter seems to be ignored. All videos from user are returned regardless if they are tagged with 'SomeTag' or not.

If the user has no videos with the provided tag I would expect the result set to be 0.

Cheers,

**Comment by chebyte** [comment]
try the last version please!

**Comment by tochman** [comment]
Hi. I get the same issue with the latest version installed.
