### ISSUE TITLE
repo too big?

### ISSUE THREAD

**Issue by masterkain** [kylejginavan/youtube_it#18]
Fetching git://github.com/kylejginavan/youtube_it.git
remote: Counting objects: 1707, done.
remote: Compressing objects: 100% (857/857), done.
remote: Total 1707 (delta 1051), reused 1244 (delta 770)
Receiving objects: 100% (1707/1707), 139.23 MiB | 272 KiB/s, done.
Resolving deltas: 100% (1051/1051), done

Took me a good while

**Comment by chebyte** [comment]
yeap you are right it has a gem in the pgk folder I going to take it

tahnks for the advice

see you

On Mon, May 23, 2011 at 3:39 PM, masterkain <
reply@reply.github.com>wrote:

> Fetching git://github.com/kylejginavan/youtube_it.git
> remote: Counting objects: 1707, done.
> remote: Compressing objects: 100% (857/857), done.
> remote: Total 1707 (delta 1051), reused 1244 (delta 770)
> Receiving objects: 100% (1707/1707), 139.23 MiB | 272 KiB/s, done.
> Resolving deltas: 100% (1051/1051), done
> 
> Took me a good while
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kylejginavan/youtube_it/issues/18

## 

---

Torres Sebastian Mauro

http://www.linkedin.com/in/maurotorres

Tuquito Team!

http://www.tuquito.org.ar
http://www.garfio.org.ar

FreeLancer Blog!

http://www.chebyte.com.ar

**Comment by masterkain** [comment]
Thanks for the fix, however you might want to apport another change:

youtube_it at /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/youtube_it-9f8fb698ab2e did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["pkg/youtube_it-1.4.1.gem"] are not files

**Comment by kylejginavan** [comment]
ok.  i added the pkg after a build so it should be available on checkout.  thanks masterkain!

**Comment by masterkain** [comment]
Hello there,
I tried again today and it appears big again:

```
Fetching git://github.com/kylejginavan/youtube_it.git
remote: Counting objects: 1794, done.
remote: Compressing objects: 100% (710/710), done.
Receiving objects:  29% (524/1794), 20.38 MiB | 286 KiB/s
```

Cheers

**Comment by kylejginavan** [comment]
I have been told the git history is causing this.  Lets see if I can clear that out to mitigate this problem.

**Comment by kylejginavan** [comment]
I ran git gc --aggressive --prune which decreased the .git folder from 275M to 140M.  Still very large though.  Going to keep researching.

**Comment by Keytwo** [comment]
Hey kyle, 
sorry for bothering you, but the problem persists.
If the history is the problem you can try to use filter-branch command.

If you don't know how you can follow the same tutorial as for removing sensitive data:
http://help.github.com/remove-sensitive-data/

Hope it helps, 'cause this can be a problem on slow connection.

See you ;)

**Comment by kylejginavan** [comment]
This is the step I followed to reduce from 275M to 140M.  I'm not sure what else to do.  I'm going to see if I can find a git expert.

**Comment by Keytwo** [comment]
Oh, sorry i thought you used the gc only, never mind ;)
Thanks for your time

**Comment by masterkain** [comment]
Sorry, this problem is not solved.

Including this gem in a brand new project means that we cannot deploy on Heroku due to maximum slug size.
We need to rewrite the repo history to remove the old .pkg permanently.

**Comment by masterkain** [comment]
or you already did

```
git filter-branch --index-filter 'git rm --cached --ignore-unmatch file_to_remove' HEAD
```

Maybe we have to ask GitHub to run a git prune? Not really a git expert, going to ask devs.

**Comment by kylejginavan** [comment]
Thanks for the heads up.  I believe I already tried this, but I just ran it again though.  Let me know if that helps.

I will also reach out to github support.

**Comment by masterkain** [comment]
Any news back from github support? I guess they might have to run a git gc --aggressive --prune server side perhaps..

**Comment by kylejginavan** [comment]
No news.  I logged the ticket almost a month ago.

**Comment by masterkain** [comment]
I even asked about this issue in IRC twice now and they also never replied to a ticket of mine.

I'll resort to using the published gem version to deploy on Heroku, it's a shame because I like keeping track of the changes by looking at my Gemfile.lock when new commits flows in.

Hopefully they will answer, but as of late github support has been pretty much sub-par and I'm even a paying customer.

Cheers and thanks for continuing development of this great gem.
