### ISSUE TITLE
Release new gem version with updated json dependency

### ISSUE THREAD

**Issue by nTraum** [kylejginavan/youtube_it#207]
Hi,

could you release a new gem version with the updated `json` gem dependency? It's already in `master` and `json 1.7.7` is outdated.

Cheers
Philipp

**Comment by silviorelli** [comment]
+1

**Comment by iansinnott** [comment]
Seriously +1

**Comment by rovitulli** [comment]
+1 :-)

**Comment by trautwein** [comment]
+1

**Comment by kylejginavan** [comment]
Done!

**Comment by nTraum** [comment]
Cheers! :dancer: :dancer: :dancer:
