### ISSUE TITLE
Video Upload to second channel

### ISSUE THREAD

**Issue by jthorsen** [kylejginavan/youtube_it#211]
My Google account has two Google+ accounts, each with a youtube channel.  I provide the dev_key for the second channel, but the upload goes to the first (default and original) channel.  Using the dev_key for either channel sends the video to the first channel.  Need a way to send to secondary channels

**Comment by jthorsen** [comment]
Solved.

**Comment by boushley** [comment]
@jthorsen  What did you do to resolve this?

**Comment by sagax** [comment]
interesting to
