### ISSUE TITLE
Json 1.8 Dependency

### ISSUE THREAD

**Issue by Shinta** [kylejginavan/youtube_it#227]
Hello,

Right now Youtube_it v 2.4 depends on Json 1.7.7, can it please depends on a newer version, like 1.8?

Thanks.

**Comment by kylejginavan** [comment]
This is in the new version!

**Comment by Shinta** [comment]
Awesome Kyle, is the new version out yet? I would like to give it a spin.

**Comment by kylejginavan** [comment]
yes
