### ISSUE TITLE
Authentication Problem with Public Data

### ISSUE THREAD

**Issue by jimblanc** [kylejginavan/youtube_it#27]
I'm trying to access a user's public subscriptions like this:

``` ruby
# Set up client
user_client = YouTubeIt::Client.new(:dev_key => "my_dev_key")

 # Load the user's activity
user_activity = user_client.subscriptions("my_username")
```

but it throws an exception: 

> AuthenticationError (Unknown)

It does this on any method that isn't support to require authentication.

Any help with this would be appreciated!

**Comment by jimblanc** [comment]
I figured it out. Apparently you have to include the developer key in the actual API call and not just the client constructor (which disagrees with the documentation).

I.E.:

``` ruby
user_client = YouTubeIt::Client.new(:dev_key => developer_key)
activity = user_client.activity("username", {"key" => developer_key})
```

**Comment by jimblanc** [comment]
Nevermind, spoke too soon.

**Comment by jimblanc** [comment]
Okay, I actually managed to fix it this time by changing authorization_headers as follows:

``` ruby
def authorization_headers
  header = {
            "X-GData-Client" => "#{@client_id}",
            "X-GData-Key"    => "key=#{@dev_key}",
          }
  begin
    if @authsub_token
      header.merge!("Authorization"  => "AuthSub token=#{@authsub_token}")
    elsif @access_token.nil? && @authsub_token.nil?
      header.merge!("Authorization"  => "GoogleLogin auth=#{auth_token}")
    end
  rescue
    # Throws an exception: Unknown if you try to access public data
  end

  header
end
```

Obviously this isn't the ideal solution but I'm not really sure how to actually fix it so I'll leave it open.

**Comment by kylejginavan** [comment]
Thanks for your patience.  I will try to get this fixed this weekend.

**Comment by chebyte** [comment]
hey jimmy this issue is fixed, you just can do

# Set up client

user_client = YouTubeIt::Client.new #now the dev_key is not mandatory

 # Load the user's activity
user_activity = user_client.subscriptions("my_username")

**Comment by jimblanc** [comment]
Cool, thanks for the fix!
