### ISSUE TITLE
Creating new client with only :dev_key causes AuthenticationError::Unknown for actions that need authentication

### ISSUE THREAD

**Issue by jch** [kylejginavan/youtube_it#28]
If I initialize a client with :dev_key, :username, and :password, then actions authenticated actions work fine (e.g. client.my_videos).  However, only specifying :dev_key does not work.  Not sure if this is expected behavior, what it's what's listed in the README.

**Comment by kylejginavan** [comment]
Using only the dev key is for getting statistics.  When creating an account you need to be authorized.

Thanks,
Kyle
