### ISSUE TITLE
comment removed

### ISSUE THREAD

**Issue by shanev** [kylejginavan/youtube_it#33]
comment removed

**Comment by shanev** [comment]
How can I respond to your comment if you removed it?

**Comment by kylejginavan** [comment]
what further do you have to say?

**Comment by shanev** [comment]
It's in the pull request. I guess I can delete my fork of youtube-g, fork youtube_it instead and submit a pull request. Simply want credit given to me and https://github.com/shaper somewhere. We worked many hours on it, and I thought the public API to seach for videos was very elegant, yet our names appear nowhere.

**Comment by kylejginavan** [comment]
I have added you and Walter as collaborators on the youtube_it project. The idea was never to shaft anyone who has contributed to it. The reason youtube_it is a fork was to give proper credit to the originators. Let me know if you still have any concerns.
