### ISSUE TITLE
warning: regexp match /.../n against to UTF-8 string

### ISSUE THREAD

**Issue by ghost** [kylejginavan/youtube_it#35]
youtube_it fails when query is an unicode string (for example):

c = YouTubeIt::Client.new
c.videos_by(:query => "спят усталые игрушки")

issues

youtube_it.rb:18: warning: regexp match /.../n against to UTF-8 string
youtube_it.rb:18: warning: regexp match /.../n against to UTF-8 string
youtube_it.rb:18: warning: regexp match /.../n against to UTF-8 string

and returns wrong list of videos  (different then one from youtube.com search ).

**Comment by chebyte** [comment]
thanks for this report, your changes was merged!
