### ISSUE TITLE
NoMethodError: undefined method `text' for nil:NilClass when accessing commetns

### ISSUE THREAD

**Issue by stpn** [kylejginavan/youtube_it#38]
Trying to get comments for videos and get NoMethodError:

This is from console:

NoMethodError: undefined method `text' for nil:NilClass        from /Users/stpn/.rvm/gems/ruby-1.9.3-p0/gems/youtube_it-2.0.1/lib/youtube_it/parser.rb:45:in`parse_entry'
        from /Users/stpn/.rvm/gems/ruby-1.9.3-p0/gems/youtube_it-2.0.1/lib/youtube_it/parser.rb:36:in `block in parse_content'
        from /Users/stpn/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rexml/element.rb:905:in`block in each'
        from /Users/stpn/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rexml/xpath.rb:67:in `each'
        from /Users/stpn/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rexml/xpath.rb:67:in`each'
        from /Users/stpn/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rexml/element.rb:905:in `each'
        from /Users/stpn/.rvm/gems/ruby-1.9.3-p0/gems/youtube_it-2.0.1/lib/youtube_it/parser.rb:35:in`parse_content'
        from /Users/stpn/.rvm/gems/ruby-1.9.3-p0/gems/youtube_it-2.0.1/lib/youtube_it/parser.rb:15:in `parse'
        from /Users/stpn/.rvm/gems/ruby-1.9.3-p0/gems/youtube_it-2.0.1/lib/youtube_it/request/video_upload.rb:160:in`comments'
        from /Users/stpn/.rvm/gems/ruby-1.9.3-p0/gems/youtube_it-2.0.1/lib/youtube_it/client.rb:122:in `comments'
        from (irb):3
        from /Users/stpn/.rvm/rubies/ruby-1.9.3-p0/bin/irb:16:in`<main>'

Any suggestions? Great gem otherwise, thanks a lot!

**Comment by chebyte** [comment]
ey there thanks for the report, this bug was fixed we going to build the gem soon, but so far you can use the code from repo

un abrazo
