### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by 2called-chaos** [kylejginavan/youtube_it#40]
It is very hard to dive into the code and the examples are not very helpful in many cases.

**Comment by stephensprinkle-zz** [comment]
Agreed.  This documentation is fantastic to show what's possible; however, a simple walk-thru for how to upload would be super helpful.  Great job on the gem btw.

**Comment by 2called-chaos** [comment]
I managed it to finish our YouTube uploader. It syncs our local videos to youtube by using information provided by a yml-file. The whole thing is a kind of a mess (it just had to be done) but I'm currently working on a better version, maybe I provide this as an example to the public.

But this might help in the meantime (but it is a bad example at all!): https://gist.github.com/2427498

**Comment by stephensprinkle-zz** [comment]
That's helpful, thanks!

I'm hoping to draft up a walk-thru re: setup once I have things stabilized with my configuration.

**Comment by mastermike14** [comment]
How do I handle the data returned by client.videos_by(:query). I thought it was an array but thats I guess its not, undefined method `[]' for #YouTubeIt::Response::VideoSearch:0x00000102ba3ff8 :/

**Comment by chebyte** [comment]
here you have an app demo how to implement the gem with rails, the code is there too

http://youtube-it.heroku.com/
