### ISSUE TITLE
git clone downloads very huge object

### ISSUE THREAD

**Issue by mahkhaled** [kylejginavan/youtube_it#44]
I noticed when I try to clone the repo from github it takes some time to download huge object > 50 MB

**Comment by egze** [comment]
Yes, very annoying

**Comment by kylejginavan** [comment]
Be annoyed no more!

git clone git@github.com:kylejginavan/youtube_it.git
Cloning into 'youtube_it'...
remote: Counting objects: 2140, done.
remote: Compressing objects: 100% (812/812), done.
remote: Total 2140 (delta 1344), reused 1916 (delta 1250)
Receiving objects: 100% (2140/2140), 502.83 KiB | 200 KiB/s, done.
Resolving deltas: 100% (1344/1344), done.
$ du -sh youtube_it/
1.4M    youtube_it/
