### ISSUE TITLE
gem dependencies

### ISSUE THREAD

**Issue by aaronchi** [kylejginavan/youtube_it#53]
As mentioned in the other ticket on faraday, you shouldn't be using hard version dependencies in your gemfile. I'm using this in a Rails app and the latest version that bundler can load right now is 2.1.1 because of the hard dependencies on old gems in the newer versions.

**Comment by chebyte** [comment]
yeap you are right I going to fix this right now

thanks

**Comment by Rio517** [comment]
I'm still seeing issues. Looks like you're hard requiring rack version 0.8.7

```
Bundler could not find compatible versions for gem "rake":
  In snapshot (Gemfile.lock):
    rake (0.9.2.2)
  In Gemfile:     
    youtube_it (>= 2.1.3) ruby depends on
      rake (= 0.8.7) 
Running `bundle update` will rebuild your snapshot from scratch, using only the gems in your Gemfile, which may resolve the conflict.  
```

**Comment by aaronchi** [comment]
looks like dependencies were relaxed in the gemfile but not the gemspec :|
