### ISSUE TITLE
Please remove jeweler dependency from the gemspec

### ISSUE THREAD

**Issue by aaronchi** [kylejginavan/youtube_it#56]
almost there ;)

**Comment by kylejginavan** [comment]
what problem is this causing?

**Comment by aaronchi** [comment]
Your gemspec should only include runtime dependencies that are required for your code to run. Jeweler is a utility for building a gem and certainly not required for interacting with youtube.

It has the effect of installing unnecessary gems in any project where this is being used.

**Comment by kylejginavan** [comment]
That response didn't answer my question.

**Comment by aaronchi** [comment]
It's not causing a specific problem. It just has the effect of adding unnecessary dependencies to projects that include this gem.

**Comment by kylejginavan** [comment]
Jeweler is necessary for me to easily manage this gem.

**Comment by aaronchi** [comment]
I understand that. You can still use jeweler to manage the gem without making it a runtime dependency

**Comment by kylejginavan** [comment]
Jeweler creates the gemspec for me.  I can see if it is possible for that to not happen.

**Comment by aaronchi** [comment]
Just add jeweler to a development group in your Gemfile.

```
group :development do
  gem 'jeweler'
end
```

This will add jeweler as a development dependency in your gemspec but won't require that it be installed for people using the gem in production.

**Comment by kylefleming** [comment]
I agree with aaronchi; it creates unnecessary bloat on our production server, slowing deployments ever so slightly, among other things.
