### ISSUE TITLE
Minus Signs 

### ISSUE THREAD

**Issue by benhill** [kylejginavan/youtube_it#63]
I have noticed that YouTube vids with a video id preceded by a minus sign don't show up in search results.  Only when removing the minus sign can it be found.

Example:

http://www.youtube.com/watch?v=-t2joAYI0JQ

[code with minus sign in video id]
video_id = "-t2joAYI0JQ"
client = YouTubeIt::Client.new
youtube_video = client.videos_by(:query => video_id).videos[0]   # => nil

[code without minus sign in video id]
video_id = "t2joAYI0JQ"
client = YouTubeIt::Client.new
youtube_video = client.videos_by(:query => video_id).videos[0]   # =>  results

**Comment by kylejginavan** [comment]
Why are you adding a minus sign here?  Seems like this isn't a problem with the gem.  Just don't pass in a minus sign ; )  I'm gonna go ahead and close this.
