### ISSUE TITLE
Playlist.videos fails with HTTP 403 for private playlist

### ISSUE THREAD

**Issue by tarko** [kylejginavan/youtube_it#72]
Video method calls YouTubeIt::Parser::VideosFeedParser directly with URL thus request doesn't have any OAuth data attached.

Example test code:

``` ruby
    c = YouTubeIt::OAuthClient.new(
        :consumer_key => GOOGLE_CONS_KEY,
        :consumer_secret => GOOGLE_CONS_SECRET,
        :dev_key => YOUTUBE_DEV_KEY
    )
    c.authorize_from_access(token, secret)

    playlists = c.playlists
    pp playlists.first
    pp playlists.first.videos
```

Results:
# <YouTubeIt::Model::Playlist:0xb6872664

 @description=nil,
 @playlist_id="515918B2F7AFA494",
 @published="2012-04-04T17:29:57.000Z",
 @response_code=nil,
 @summary=nil,
 @title="testplaylist",
 @xml=nil>
/var/lib/gems/1.8/gems/youtube_it-2.0.1/lib/youtube_it/parser.rb:8:in `initialize': 403 (OpenURI::HTTPError)
        from /var/lib/gems/1.8/gems/youtube_it-2.0.1/lib/youtube_it/model/playlist.rb:6:in`new'
        from /var/lib/gems/1.8/gems/youtube_it-2.0.1/lib/youtube_it/model/playlist.rb:6:in `videos'
        from providers.rb:29

**Comment by chebyte** [comment]
this is fixed thanks for report!
