### ISSUE TITLE
YouTube_It::Client::OAuth2Client#current_user is a pointless waste of an API call

### ISSUE THREAD

**Issue by yaauie** [kylejginavan/youtube_it#76]
https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/client.rb#L450

`YouTubeIt::Upload::VideoUpload` does not need to know the username unless auth is via AuthSub/ClientLogin. This was a dirty hack in the first place, and it wasn't even necessary.

This call is damaging because it means each client has an API-call overhead of N+1, which is especially damaging for low N, such as when each client is only intending to make one request. With it in place on our distributed system (which makes one call per client), 100% of my rate limits (which happened _often_) were coming from this call, but with it removed, no limits were getting hit at all, even with high concurrency.

**Comment by chebyte** [comment]
can you explain better? I dont understand you

**Comment by yaauie** [comment]
I shouldn't have pointed my links to `master`; they failed to point to the correct line numbers as `master` changed `:)`

## Problem
-  `YouTubeIt::Upload::VideoUpload` _only_ needs to know who the current user is `IFF` the authentication mode is AuthSub/ClientLogin.
- [YouTubeIt::OAuth2Client#client](https://github.com/kylejginavan/youtube_it/blob/1009998a103eff87f75402a6f4ed0b898c121bca/lib/youtube_it/client.rb#L481) needlessly passes `current_user` to `YouTubeIt::Upload::VideoUpload#new`
- Since `YouTubeIt::OAuth2Client#initialize` does not set a value for `current_user`, a [method was written](https://github.com/kylejginavan/youtube_it/blob/1009998a103eff87f75402a6f4ed0b898c121bca/lib/youtube_it/client.rb#L466) to deduce the current user by making a call directly through the access token for the default user, parsing the XML, and returning a result.
- The call to get the `current_user` at this point is not necessary, and thus a waste of an API call.

## Result
- Every `YouTubeIt::OAuth2Client` created has an overhead of one API call to `http://gdata.youtube.com/feeds/api/users/default` (`N+1`, `N` being the number of API requests desired).
- For low `N`, this approaches `2N` (consider only needing to make 1 api call per client created and making 2 instead).
- The API endpoint `http://gdata.youtube.com/feeds/api/users/default` ends up getting hammered with API requests (that are not even necessary), invoking `overLimit` errors; in my experience, `overLimit` errors were statistically _much_ more likely to come from this request, which isn't wrapped in YouTubeIt's normal error handling, so we just got a generic authentication error with the XML response unparsed. I suspect that their (unpublished) rate limits kick in per api endpoint, or at least that's a factor.

## Solution
- Use [YouTubeIt::Client#current_user](https://github.com/kylejginavan/youtube_it/blob/1009998a103eff87f75402a6f4ed0b898c121bca/lib/youtube_it/client.rb#L233) when you need to get the current user (which should be memoized since it is a small value that will not change, and regenerating it is expensive) instead of overriding it in `YouTubeIt::OAuth2Client#current_user` 
- Don't pass `current_user` in `YouTubeIt::Upload::VideoUpload#initialize` for Oauth2.

**Comment by chebyte** [comment]
oka now is clear sound good I'll make these changes thanks!
