### ISSUE TITLE
Its possible add progress bar?

### ISSUE THREAD

**Issue by hyperrjas** [kylejginavan/youtube_it#92]
Hello I have this progress bar:

http://jsfiddle.net/xXM2z/68/

Its possbile add a progress bar for upload the video to youtube?

Thank you very much!

**Comment by chebyte** [comment]
hey there  I can't think of a good solution for browser-based uploads, since 
that involves your user's web browser making a direct HTTP POST to youtube servers

you can see here more

https://groups.google.com/group/youtube-api-gdata/browse_thread/thread/ae766afe009e11cf/983c6b95475b14b3?pli=1

**Comment by hyperrjas** [comment]
Thank you very much. I will add an loading.gif icon while the video is uploaded :D.

Thank you very much!
