### ISSUE TITLE
Its possible check if is a duplicate video upload?

### ISSUE THREAD

**Issue by hyperrjas** [kylejginavan/youtube_it#93]
Hello, its possible get the response from youtube for duplicate videos uploaded? for show error in controller and it does not save the object in database?

Thank you very much!

**Comment by chebyte** [comment]
if you see youtube api documentation

```
https://developers.google.com/youtube/2.0/reference
```

if you see when you upload duplicate video google return as code request DUPLICATE but
for the moment you cant do it with our gem  cause when you upload a video the gem return a video as result instead the status and code request

I will try to add a featured for this when I get a little of free time

cheers

**Comment by hyperrjas** [comment]
Thank you @chebyte. Has there been any change in this gem, to see if a video is duplicated after upload?

**Comment by chebyte** [comment]
hi there I was checking and is not possible I just upload a same video many time and youtube api always return 201 status (this is means ok) but I going to think some way to figure out this
