### ISSUE TITLE
its possible autoplay?

### ISSUE THREAD

**Issue by hyperrjas** [kylejginavan/youtube_it#94]
Hello I want to know if is possible add **autoplay option** in video player.

I dont find this option in readme.

Thank you very much

**Comment by chebyte** [comment]
for the moment just embed_html5 supports params, but I going to add support params for flash embed soon

but you can do

```
video.embed_html5(:url_params => {:autoplay => "1")
```

**Comment by hyperrjas** [comment]
Thank you very much, but I have tried with the next code, but the autoplay it does not works for me :(:

```
raw yt_client.my_video(@object.yt_video_id).embed_html5(:url_params => {:autoplay => "1"})
```

Where have I the problem?

Thank you!

**Comment by chebyte** [comment]
your code is ok, we just pulled the new release of gem so please update the gem to 2.1.15 with the last version your code has to works, please try and tell me

**Comment by hyperrjas** [comment]
Woow now the autoplay does works fine :D. Thank you very much @chebyte!

**Comment by chebyte** [comment]
thanks you for report the problem!

**Comment by hyperrjas** [comment]
;) Thank you to you for your help and for your help!
