### ISSUE TITLE
Link to a URL in youtube description box 

### ISSUE THREAD

**Issue by hyperrjas** [kylejginavan/youtube_it#98]
Hi, I want make a custom modification in this gem for people who are on youtube, can find the website where the user uploaded the video.

In youtube description I have seen a lot of videos that have a url before the description you can see a example:

http://www.youtube.com/watch?v=AhdoE8GQeFo

and a tutorial for do it manual mode:

http://www.youtube.com/watch?v=1hyJfRMyKeI

When I make a new object in my app, I get a url with slug attribute sth like:

http://mydomain.com/object/object-title-slug

I have an attribute :slug. This attribute have a value **object-title-slug**

I want send to youtube this url **http://mydomain.com/object/object-title-slug** to description box before the description text sth like.

**http://mydomain.com/object/object-title-slug this is the full description...bla bla bla....**

Its possible add this functionality to this gem?

would be very grateful and would be helpful to youtube users.

**Comment by chebyte** [comment]
can you just add the link to the desc when you upload the video using the api?

like this

```
$ client.video_upload(File.open("test.mov"), :title => "test",:description => 'some description http://example.com', :category => 'People',:keywords => %w[cool blah test])
```

it is not working?
